#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x2EF56372BA48CD1B (felisiak.mariusz@gmail.com)
#
Name     : pypi-django
Version  : 4.1.1
Release  : 10
URL      : https://files.pythonhosted.org/packages/ca/78/49ac0899f74c485acbf96bc8a5ea6a87575edb06faa9911057cacd505ba9/Django-4.1.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/ca/78/49ac0899f74c485acbf96bc8a5ea6a87575edb06faa9911057cacd505ba9/Django-4.1.1.tar.gz
Source1  : https://files.pythonhosted.org/packages/ca/78/49ac0899f74c485acbf96bc8a5ea6a87575edb06faa9911057cacd505ba9/Django-4.1.1.tar.gz.asc
Summary  : A high-level Python web framework that encourages rapid development and clean, pragmatic design.
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause MIT OFL-1.1
Requires: pypi-django-bin = %{version}-%{release}
Requires: pypi-django-license = %{version}-%{release}
Requires: pypi-django-python = %{version}-%{release}
Requires: pypi-django-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(asgiref)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(sqlparse)
BuildRequires : pypi(tzdata)
BuildRequires : pypi(wheel)

%description
Django
        ======
        
        Django is a high-level Python web framework that encourages rapid development
        and clean, pragmatic design. Thanks for checking it out.
        
        All documentation is in the "``docs``" directory and online at

%package bin
Summary: bin components for the pypi-django package.
Group: Binaries
Requires: pypi-django-license = %{version}-%{release}

%description bin
bin components for the pypi-django package.


%package license
Summary: license components for the pypi-django package.
Group: Default

%description license
license components for the pypi-django package.


%package python
Summary: python components for the pypi-django package.
Group: Default
Requires: pypi-django-python3 = %{version}-%{release}

%description python
python components for the pypi-django package.


%package python3
Summary: python3 components for the pypi-django package.
Group: Default
Requires: python3-core
Provides: pypi(django)
Requires: pypi(asgiref)
Requires: pypi(sqlparse)
Requires: pypi(tzdata)

%description python3
python3 components for the pypi-django package.


%prep
%setup -q -n Django-4.1.1
cd %{_builddir}/Django-4.1.1
pushd ..
cp -a Django-4.1.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1664461367
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-django
cp %{_builddir}/Django-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-django/baf11129ce63c4eef654f39a360b31cfc7d1ac67 || :
cp %{_builddir}/Django-%{version}/django/contrib/admin/static/admin/css/vendor/select2/LICENSE-SELECT2.md %{buildroot}/usr/share/package-licenses/pypi-django/016d84ac0cab22a77e44e7182bb1691d97449696 || :
cp %{_builddir}/Django-%{version}/django/contrib/admin/static/admin/fonts/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-django/47b573e3824cd5e02a1a3ae99e2735b49e0256e4 || :
cp %{_builddir}/Django-%{version}/django/contrib/admin/static/admin/img/LICENSE %{buildroot}/usr/share/package-licenses/pypi-django/25180b3c1e27c6d700e4e037e53b970fe36b1f3e || :
cp %{_builddir}/Django-%{version}/django/contrib/admin/static/admin/js/vendor/jquery/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-django/3a62584221d4f6b6a2ee95361c142b4e6e69d1ef || :
cp %{_builddir}/Django-%{version}/django/contrib/admin/static/admin/js/vendor/select2/LICENSE.md %{buildroot}/usr/share/package-licenses/pypi-django/016d84ac0cab22a77e44e7182bb1691d97449696 || :
cp %{_builddir}/Django-%{version}/django/contrib/admin/static/admin/js/vendor/xregexp/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-django/49374697c5dbcdfc34349dc1c8566c0bc4759d1f || :
cp %{_builddir}/Django-%{version}/django/contrib/gis/gdal/LICENSE %{buildroot}/usr/share/package-licenses/pypi-django/f0fda12a002635b7014205a973222bbc34df78de || :
cp %{_builddir}/Django-%{version}/django/contrib/gis/geos/LICENSE %{buildroot}/usr/share/package-licenses/pypi-django/3f9aeadb484dd83ead5656f1bc870e7685607bee || :
cp %{_builddir}/Django-%{version}/django/dispatch/license.txt %{buildroot}/usr/share/package-licenses/pypi-django/a1f11ae702923c95226800ca5172b00b3f975386 || :
cp %{_builddir}/Django-%{version}/docs/_theme/djangodocs/static/fontawesome/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-django/c48a7d100730cfd1b71d3830179dbf40fdd9c3c2 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/django-admin

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-django/016d84ac0cab22a77e44e7182bb1691d97449696
/usr/share/package-licenses/pypi-django/25180b3c1e27c6d700e4e037e53b970fe36b1f3e
/usr/share/package-licenses/pypi-django/3a62584221d4f6b6a2ee95361c142b4e6e69d1ef
/usr/share/package-licenses/pypi-django/3f9aeadb484dd83ead5656f1bc870e7685607bee
/usr/share/package-licenses/pypi-django/47b573e3824cd5e02a1a3ae99e2735b49e0256e4
/usr/share/package-licenses/pypi-django/49374697c5dbcdfc34349dc1c8566c0bc4759d1f
/usr/share/package-licenses/pypi-django/a1f11ae702923c95226800ca5172b00b3f975386
/usr/share/package-licenses/pypi-django/baf11129ce63c4eef654f39a360b31cfc7d1ac67
/usr/share/package-licenses/pypi-django/c48a7d100730cfd1b71d3830179dbf40fdd9c3c2
/usr/share/package-licenses/pypi-django/f0fda12a002635b7014205a973222bbc34df78de

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
